name: github-deployment-pipeline

on:
  push:
    branches:
    - main

jobs: 
  main:
    name: install-test-build-deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npm run test
    - run: npm run test:cov
    - run: npm run build